---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="= 5.2.0"
  - rvm: 2.3.7
    env: PUPPET_GEM_VERSION="= 5.3.7"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="= 5.4.0"
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5.5"
branches:
  only:
    - master
